"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 21:39:02.522078
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apk_files',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('quarantine_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sha256')
    )
    with op.batch_alter_table('apk_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apk_files_sha256'), ['sha256'], unique=False)

    op.create_table('audit_blocks',
    sa.Column('block_index', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.Column('signature_json', sa.Text(), nullable=False),
    sa.Column('key_id', sa.String(length=32), nullable=False),
    sa.CheckConstraint('block_index >= 0', name='ck_block_index'),
    sa.PrimaryKeyConstraint('block_index'),
    sa.UniqueConstraint('block_hash'),
    sa.UniqueConstraint('previous_hash')
    )
    with op.batch_alter_table('audit_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_blocks_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_blocks_subject'), ['subject'], unique=False)

    op.create_table('audit_tamper_backups',
    sa.Column('block_index', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('original_json', sa.Text(), nullable=False),
    sa.Column('tampered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('block_index')
    )
    op.create_table('trusted_baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('baseline_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('app_version_name', sa.String(length=128), nullable=True),
    sa.Column('app_version_code', sa.Integer(), nullable=True),
    sa.Column('apk_sha256', sa.String(length=64), nullable=False),
    sa.Column('apk_size', sa.Integer(), nullable=False),
    sa.Column('certificate_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('merkle_root', sa.String(length=64), nullable=False),
    sa.Column('files_json', sa.Text(), nullable=False),
    sa.Column('profile_json', sa.Text(), nullable=False),
    sa.Column('profile_sha256', sa.String(length=64), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_hashes_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('signature_json', sa.Text(), nullable=True),
    sa.Column('signing_key_id', sa.String(length=32), nullable=True),
    sa.CheckConstraint("status IN ('pending','approved','rejected','revoked')", name='ck_baseline_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_name', 'baseline_version', name='uq_baseline_package_version')
    )
    with op.batch_alter_table('trusted_baselines', schema=None) as batch_op:
        batch_op.create_index('ix_baseline_package_status', ['package_name', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trusted_baselines_certificate_sha256'), ['certificate_sha256'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('admin','analyst')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('apk_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('submitted_by', sa.String(length=64), nullable=True),
    sa.Column('package_name', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('queued','running','done','failed')", name='ck_job_status'),
    sa.ForeignKeyConstraint(['apk_sha256'], ['apk_files.sha256'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_apk_sha256'), ['apk_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_package_name'), ['package_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('engine_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('engine_name', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_status_job_id'), ['job_id'], unique=False)

    op.create_table('trust_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('integrity_status', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('rules_fired_json', sa.Text(), nullable=False),
    sa.Column('inputs_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trust_scores')
    with op.batch_alter_table('engine_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_status_job_id'))

    op.drop_table('engine_status')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_package_name'))
        batch_op.drop_index(batch_op.f('ix_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_apk_sha256'))

    op.drop_table('jobs')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))

    op.drop_table('auth_sessions')
    op.drop_table('users')
    with op.batch_alter_table('trusted_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trusted_baselines_certificate_sha256'))
        batch_op.drop_index('ix_baseline_package_status')

    op.drop_table('trusted_baselines')
    op.drop_table('audit_tamper_backups')
    with op.batch_alter_table('audit_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_blocks_subject'))
        batch_op.drop_index(batch_op.f('ix_audit_blocks_event_type'))

    op.drop_table('audit_blocks')
    with op.batch_alter_table('apk_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apk_files_sha256'))

    op.drop_table('apk_files')
    # ### end Alembic commands ###
